version: "3"
services:
  react-front:
    image: example/client
    build:
      context: ./client
    ports:
      - 8080:8080
  flask-backend:
    image: example/server
    build:
      context: ./server
    ports: 
      - "5000:5000"
